import React, { useEffect } from 'react'

const Banner = () => {
    useEffect(() => {
        var TweenLite = require('https://cdnjs.cloudflare.com/ajax/libs/gsap/2.0.1/TweenMax.min.js?ver=5.3.2  ');
        require('../../js/revolution.tools.min.js');
        require('../../js/revolution.extension.min.js');
        require('../../js/revoulation.js');
    }, [])
    
    return (
        <>
            {/* home banner end */}
            <div id="wrapper" className="wrapper">
                {/* START REVOLUTION SLIDER */}
                <div className="slider-revoluation">
                    <div id="rev_slider_6_1" className="rev_slider rev_slider_6_1 fullscreenbanner" style={{ display: 'none' }} data-version="5.4.7">
                        <ul>
                            {/* SLIDE  */}
                            <li data-index="rs-16" data-transition="slideoverdown" data-slotamount="default" data-hideafterloop={0} data-hideslideonmobile="off" data-easein="Power3.easeInOut" data-easeout="Power3.easeInOut" data-masterspeed={1500} data-rotate={0} data-saveperformance="off" data-title="Intro" data-param1 data-param2 data-param3 data-param4 data-param5 data-param6 data-param7 data-param8 data-param9 data-param10 data-description>
                                {/* MAIN IMAGE */}
                                <img src="images/revoulation/dummy.webp" alt="" data-lazyload="images/revoulation/banner.webp" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" className="rev-slidebg lazy" data-no-retina />
                                {/* LAYERS */}
                                {/* LAYER NR. 1 */}
                                <div className="tp-caption   tp-resizeme rs-parallaxlevel-3" id="slide-16-layer-10" data-x="['left','left','left','left']" data-hoffset="['270','270','270','270']" data-y="['middle','middle','middle','middle']" data-voffset="['-100','-100','-100','-100']" data-width="none" data-height="none" data-whitespace="normal" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2000,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.8;sY:0.8;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 5 }}>
                                    <div className="rs-looped rs-slideloop " data-easing data-speed={3} data-xs={0} data-xe={0} data-ys={10} data-ye={-10}><img src="images/revoulation/dummy.webp" alt="" data-ww="['163px','163px','163px','163px']" data-hh="['166px','166px','166px','166px']" data-lazyload="images/revoulation/slider-agency-website-slide-01-image-02.webp" data-no-retina className="one lazy" data-speed="0.08" data-revert="true" />
                                    </div>
                                </div>
                                {/* LAYER NR. 2 */}
                                <div className="tp-caption  tp-resizeme rs-parallaxlevel-3" id="slide-16-layer-16" data-x="['left','left','left','left']" data-hoffset="['-160','-160','-160','-160']" data-y="['bottom','bottom','bottom','bottom']" data-voffset="['-160','-160','-160','-160']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1900,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.8;sY:0.8;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 6 }}>
                                    <div className="rs-looped rs-wave" data-speed={3} data-angle={0} data-radius={10} data-origin="50% 50%"><img src="images/revoulation/dummy.webp" alt="" data-ww="['433px','433px','433px','433px']" data-hh="['433px','433px','433px','433px']" data-lazyload="images/revoulation/slider-agency-website-slide-01-image-06.webp" data-no-retina className="one lazy" data-speed="0.08" data-revert="true" />
                                    </div>
                                </div>
                                {/* LAYER NR. 3 */}
                                <div className="tp-caption tp-resizeme rs-parallaxlevel-3" id="slide-16-layer-12" data-x="['left','left','left','left']" data-hoffset="['100','100','100','100']" data-y="['bottom','bottom','bottom','bottom']" data-voffset="['0','0','0','0']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1900,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.8;sY:0.8;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 7 }}>
                                    <div className="rs-looped rs-pulse" data-easing="Linear.easeNone" data-speed={4} data-zoomstart={1} data-zoomend="0.9"><img src="images/revoulation/dummy.webp" alt="" data-ww="['324px','324px','324px','324px']" data-hh="['325px','325px','325px','325px']" data-lazyload="images/revoulation/slider-agency-website-slide-01-image-01.webp" data-no-retina className="one lazy" data-speed="0.08" data-revert="true" />
                                    </div>
                                </div>
                                {/* LAYER NR. 4 */}
                                <div className="tp-caption tp-resizeme rs-parallaxlevel-3" id="slide-16-layer-13" data-x="['right','right','right','right']" data-hoffset="['250','250','250','250']" data-y="['top','top','top','top']" data-voffset="['130','130','130','130']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2200,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.8;sY:0.8;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 8 }}>
                                    <div className="rs-looped rs-slideloop" data-easing="Linear.easeNone" data-speed={4} data-xs={0} data-xe={0} data-ys={-20} data-ye={20}><img src="images/revoulation/dummy.webp" alt="" data-ww="['129px','129px','129px','129px']" data-hh="['137px','137px','137px','137px']" data-lazyload="images/revoulation/slider-agency-website-slide-01-image-03.webp" data-no-retina className="one lazy" data-speed="0.08" data-revert="true" />
                                    </div>
                                </div>
                                {/* LAYER NR. 5 */}
                                <div className="tp-caption tp-resizeme" id="slide-16-layer-14" data-x="['right','right','right','right']" data-hoffset="['110','110','110','110']" data-y="['bottom','bottom','bottom','bottom']" data-voffset="['85','85','85','85']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2100,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.8;sY:0.8;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 9 }}><img src="images/revoulation/dummy.webp" alt="" data-ww="['164px','164px','164px','164px']" data-hh="['164px','164px','164px','164px']" data-lazyload="images/revoulation/slider-agency-website-slide-01-image-05.webp" data-no-retina className="one lazy" data-speed="0.08" data-revert="true" /> </div>
                                {/* LAYER NR. 6 */}
                                <div className="tp-caption tp-resizeme rs-parallaxlevel-2" id="slide-16-layer-15" data-x="['right','right','right','right']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-130','-130','-130','-130']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2000,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 10 }}>
                                    <div className="rs-looped rs-slideloop" data-easing="Power1.easeIn" data-speed={3} data-xs={0} data-xe={20} data-ys={0} data-ye={0}><img src="images/revoulation/dummy.webp" alt="" data-ww="['187px','187px','187px','187px']" data-hh="['351px','351px','351px','351px']" className="lazy" data-lazyload="images/revoulation/slider-agency-website-slide-01-image-04.webp" data-no-retina /> </div>
                                </div>
                                {/* LAYER NR. 7 */}
                                <div className="tp-caption rs-parallaxlevel-5" id="slide-16-layer-1" data-x="['center','center','center','center']" data-hoffset="['48','-45','54','32']" data-y="['middle','middle','bottom','bottom']" data-voffset="['169','103','-219','-188']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="off" data-responsive="off" data-frames="[{&quot;delay&quot;:1000,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 11 }}><img src="images/revoulation/dummy.webp" alt="" data-ww="['960px','700px','600px','500px']" className="lazy" data-hh="['930px','678px','581px','484px']" data-lazyload="images/revoulation/slider-agency-website-slide-01-macbook-frame.webp" data-no-retina /> </div>
                                {/* LAYER NR. 8 */}
                                <div className="tp-caption rs-parallaxlevel-5" id="slide-16-layer-2" data-x="['center','center','center','center']" data-hoffset="['0','-89','15','-2']" data-y="['middle','middle','bottom','bottom']" data-voffset="['-14','-46','68','43']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="off" data-responsive="off" data-frames="[{&quot;delay&quot;:1500,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0deg;rY:0;rZ:0;sX:2;sY:2;skX:0;skY:0;opacity:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 12 }}><img src="images/revoulation/dummy.webp" className="lazy" alt="" data-ww="['654px','450px','400px','350px']" data-hh="['409px','290px','258px','226px']" data-lazyload="images/revoulation/slider-agency-website-slide-01-macbook-content.webp" data-no-retina /> </div>
                                {/* LAYER NR. 9 */}
                                <div className="tp-caption tp-shape tp-shapewrapper  tp-resizeme rs-parallaxlevel-3" id="slide-16-layer-3" data-x="['right','right','center','center']" data-hoffset="['20','0','-20','-25']" data-y="['middle','middle','top','top']" data-voffset="['0','0','130','120']" data-width="['350','350','350','330']" data-height="['350','350','350','330']" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1500,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 13, backgroundColor: 'rgb(34,34,34)', boxShadow: '-20px 20px 50px rgba(0, 0, 0, 0.09)' }}>
                                </div>
                                {/* LAYER NR. 10 */}
                                <div className="tp-caption Agency-SmallTitle   tp-resizeme rs-parallaxlevel-3 text-white" id="slide-16-layer-4" data-x="['right','right','center','center']" data-hoffset="['40','20','-20','-25']" data-y="['middle','middle','top','top']" data-voffset="['-88','-98','170','154']" data-width={295} data-height="none" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2000,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 14, minWidth: '295px', maxWidth: '295px', whiteSpace: 'normal', letterSpacing: '3px', textTransform: 'uppercase' }}>
                                    DISTINCT <br /> SOLUTIONS </div>
                                {/* LAYER NR. 11 */}
                                <div className="tp-caption Agency-SmallContent   tp-resizeme rs-parallaxlevel-3 text-white" id="slide-16-layer-5" data-x="['right','right','center','center']" data-hoffset="['40','20','-20','-25']" data-y="['middle','middle','top','top']" data-voffset="['20','20','290','270']" data-fontsize="['14','14','14','15']" data-lineheight="['22','22','22','24']" data-fontweight="['500','500','500','400']" data-width={295} data-height="none" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2150,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 15, minWidth: '295px', maxWidth: '295px', whiteSpace: 'normal' }}>
                                    In a world where technology constantly evolves, we believe diversity is essential for staying ahead of the curve. Let us help you develop unique solutions that celebrate and embrace diversity.
                                </div>
                                {/* LAYER NR. 12 */}
                                <a className="tp-caption Agency-SmallLink   tp-resizeme rs-parallaxlevel-3 text-white" href="about.php" target="_self" id="slide-16-layer-6" data-x="['right','right','center','center']" data-hoffset="['235','210','-20','-25']" data-y="['middle','middle','top','top']" data-voffset="['108','108','392','382']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-actions data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2300,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;300&quot;,&quot;ease&quot;:&quot;Power1.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgba(255,255,255,1);bc:rgb(248,185,32);bw:0 0 2px 0;&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[5,5,5,5]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 111, whiteSpace: 'nowrap', borderColor: 'rgba(221,221,221,0.11)', cursor: 'pointer', textDecoration: 'none' }}>Read
                                    more <span className="fa fa-arrow-right" style={{ fontSize: '12px', color: '#F8B920', marginLeft: '8px' }}>
                                    </span> </a>
                                {/* LAYER NR. 13 */}
                                <div className="tp-caption Agency-NavButton rev-btn  tp-resizeme rs-parallaxlevel-3" id="slide-16-layer-8" data-x="['right','right','center','center']" data-hoffset="['72','52','182','172']" data-y="['middle','middle','top','top']" data-voffset="['202','202','182','172']" data-width={50} data-height={50} data-whitespace="nowrap" data-type="button" data-actions="[{&quot;event&quot;:&quot;click&quot;,&quot;action&quot;:&quot;jumptoslide&quot;,&quot;slide&quot;:&quot;previous&quot;,&quot;delay&quot;:&quot;&quot;}]" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2400,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;300&quot;,&quot;ease&quot;:&quot;Power1.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgba(255,255,255,1);bg:rgb(34,34,34);bs:solid;bw:0 0 0 0;&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 17, minWidth: '50px', maxWidth: '50px', whiteSpace: 'nowrap', fontFamily: 'Arial', borderColor: 'rgba(0,0,0,1)', outline: 'none', boxShadow: 'none', boxSizing: 'border-box', MozBoxSizing: 'border-box', WebkitBoxSizing: 'border-box', cursor: 'pointer' }}>
                                    <i className="fas fa-angle-left" />
                                </div>
                                {/* LAYER NR. 14 */}
                                <div className="tp-caption Agency-NavButton rev-btn  tp-resizeme rs-parallaxlevel-3" id="slide-16-layer-7" data-x="['right','right','center','center']" data-hoffset="['20','0','182','172']" data-y="['middle','middle','top','top']" data-voffset="['202','202','130','120']" data-width={50} data-height={50} data-whitespace="nowrap" data-type="button" data-actions="[{&quot;event&quot;:&quot;click&quot;,&quot;action&quot;:&quot;jumptoslide&quot;,&quot;slide&quot;:&quot;next&quot;,&quot;delay&quot;:&quot;&quot;}]" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2500,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;300&quot;,&quot;ease&quot;:&quot;Power1.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgba(255,255,255,1);bg:rgb(34,34,34);bs:solid;bw:0 0 0 0;&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 18, minWidth: '50px', maxWidth: '50px', whiteSpace: 'nowrap', fontFamily: 'Arial', borderColor: 'rgba(0,0,0,1)', outline: 'none', boxShadow: 'none', boxSizing: 'border-box', MozBoxSizing: 'border-box', WebkitBoxSizing: 'border-box', cursor: 'pointer' }}>
                                    <i className="fas fa-angle-right" />
                                </div>
                            </li>
                            {/* SLIDE  */}
                            <li data-index="rs-17" data-transition="slideoverdown" data-slotamount="default" data-hideafterloop={0} data-hideslideonmobile="off" data-easein="Power3.easeInOut" data-easeout="Power3.easeInOut" data-masterspeed={1500} data-rotate={0} data-saveperformance="off" data-title="Responsive" data-param1 data-param2 data-param3 data-param4 data-param5 data-param6 data-param7 data-param8 data-param9 data-param10 data-description>
                                {/* MAIN IMAGE */}
                                <img src="images/revoulation/dummy.webp" alt="" data-lazyload="images/revoulation/banner.webp" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" className="rev-slidebg lazy" data-no-retina />
                                {/* LAYERS */}
                                {/* LAYER NR. 15 */}
                                <div className="tp-caption   tp-resizeme rs-parallaxlevel-3" id="slide-17-layer-13" data-x="['left','left','left','left']" data-hoffset="['260','260','260','260']" data-y="['top','top','top','top']" data-voffset="['240','240','240','240']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1010,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.8;sY:0.8;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 5 }}>
                                    <div className="rs-looped rs-slideloop" data-easing data-speed={3} data-xs={0} data-xe={0} data-ys={-20} data-ye={20}><img src="images/revoulation/dummy.webp" alt="" data-ww="['120px','120px','120px','120px']" data-hh="['127px','127px','127px','127px']" data-lazyload="images/revoulation/slider-agency-website-slide-02-image-02.webp" data-no-retina className="one lazy" data-speed="0.08" data-revert="true" />
                                    </div>
                                </div>
                                {/* LAYER NR. 16 */}
                                <div className="tp-caption   tp-resizeme rs-parallaxlevel-3" id="slide-17-layer-14" data-x="['right','right','right','right']" data-hoffset="['60','60','59','59']" data-y="['middle','middle','middle','middle']" data-voffset="['-200','-200','-201','-201']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1310,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.8;sY:0.8;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 6 }}>
                                    <div className="rs-looped rs-wave" data-speed={4} data-angle={0} data-radius="10px" data-origin="50% 50%"><img src="images/revoulation/dummy.webp" alt="" data-ww="['150px','150px','150px','150px']" data-hh="['152px','152px','152px','152px']" data-lazyload="images/revoulation/slider-agency-website-slide-02-image-01.webp" data-no-retina className="one lazy" data-speed="0.08" data-revert="true" />
                                    </div>
                                </div>
                                {/* LAYER NR. 17 */}
                                <div className="tp-caption   rs-parallaxlevel-5" id="slide-17-layer-1" data-x="['center','center','center','center']" data-hoffset="['0','20','60','20']" data-y="['middle','middle','bottom','bottom']" data-voffset="['60','0','30','20']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="off" data-responsive="off" data-frames="[{&quot;delay&quot;:1000,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 7 }}><img src="images/revoulation/dummy.webp" alt="" data-ww="['434px','430px','360px','200px']" className="lazy" data-hh="['588px','540px','452px','251px']" data-lazyload="images/revoulation/slider-agency-website-slide-02-ipad-frame.webp" data-no-retina /> </div>
                                {/* LAYER NR. 18 */}
                                <div className="tp-caption   rs-parallaxlevel-5" id="slide-17-layer-2" data-x="['center','center','center','center']" data-hoffset="['-14','20','60','20']" data-y="['middle','middle','bottom','bottom']" data-voffset="['40','5','97','56']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="off" data-responsive="off" data-frames="[{&quot;delay&quot;:1500,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0deg;rY:0;rZ:0;sX:2;sY:2;skX:0;skY:0;opacity:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 8 }}><img src="images/revoulation/dummy.webp" alt="" data-ww="['343px','290px','242px','134px']" className="lazy" data-hh="['456px','372px','310px','172px']" data-lazyload="images/revoulation/slider-agency-website-slide-02-ipad-content.webp" data-no-retina /> </div>
                                {/* LAYER NR. 19 */}
                                <div className="tp-caption   rs-parallaxlevel-4" id="slide-17-layer-9" data-x="['center','center','center','center']" data-hoffset="['-381','-158','-92','-57']" data-y="['middle','middle','bottom','bottom']" data-voffset="['60','60','15','14']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="off" data-responsive="off" data-frames="[{&quot;delay&quot;:1250,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 9 }}><img src="images/revoulation/dummy.webp" alt="" data-ww="['240px','260px','220px','120px']" className="lazy" data-hh="['448px','450px','381px','208px']" data-lazyload="images/revoulation/slider-agency-website-slide-02-iphone-frame.webp" data-no-retina /> </div>
                                {/* LAYER NR. 20 */}
                                <div className="tp-caption   tp-resizeme" id="slide-17-layer-11" data-x="['center','center','center','center']" data-hoffset="['-570','-570','-570','-570']" data-y="['middle','middle','middle','middle']" data-voffset="['55','55','55','55']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1250,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 10 }}><img src="images/revoulation/dummy.webp" alt="" data-ww="['35px','35px','35px','35px']" className="lazy" data-hh="['333px','333px','333px','333px']" data-lazyload="images/revoulation/slider-agency-website-slide-02-pen.webp" data-no-retina />
                                </div>
                                {/* LAYER NR. 21 */}
                                <div className="tp-caption   rs-parallaxlevel-4" id="slide-17-layer-10" data-x="['center','center','center','center']" data-hoffset="['-392','-157','-92','-57']" data-y="['middle','middle','bottom','bottom']" data-voffset="['45','60','85','51']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="off" data-responsive="off" data-frames="[{&quot;delay&quot;:1750,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0deg;rY:0;rZ:0;sX:2;sY:2;skX:0;skY:0;opacity:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 11 }}><img src="images/revoulation/dummy.webp" alt="" data-ww="['186px','170px','144px','78px']" className="lazy" data-hh="['395px','286px','242px','131px']" data-lazyload="images/revoulation/slider-agency-website-slide-02-iphone-content.webp" data-no-retina /> </div>
                                {/* LAYER NR. 22 */}
                                <div className="tp-caption tp-shape tp-shapewrapper  tp-resizeme rs-parallaxlevel-3" id="slide-17-layer-3" data-x="['right','right','center','center']" data-hoffset="['19','0','-25','-25']" data-y="['middle','middle','top','top']" data-voffset="['28','-2','130','120']" data-width="['350','350','350','330']" data-height="['350','350','350','330']" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1500,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 12, backgroundColor: 'rgb(34,34,34)' }}>
                                </div>
                                {/* LAYER NR. 23 */}
                                <div className="tp-caption Agency-SmallTitle   tp-resizeme rs-parallaxlevel-3 text-white" id="slide-17-layer-4" data-x="['right','right','center','center']" data-hoffset="['40','20','-25','-25']" data-y="['middle','middle','top','top']" data-voffset="['-60','-98','164','154']" data-width={295} data-height="none" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2000,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 13, minWidth: '295px', maxWidth: '295px', whiteSpace: 'normal', letterSpacing: '3px', textTransform: 'uppercase' }}>
                                    Perfectly<br />
                                    Responsive </div>
                                {/* LAYER NR. 24 */}
                                <div className="tp-caption Agency-SmallContent   tp-resizeme rs-parallaxlevel-3 text-white" id="slide-17-layer-5" data-x="['right','right','center','center']" data-hoffset="['40','20','-25','-25']" data-y="['middle','middle','top','top']" data-voffset="['48','8','280','271']" data-fontsize="['14','14','14','15']" data-lineheight="['22','22','22','24']" data-width={295} data-height="none" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2150,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 14, minWidth: '295px', maxWidth: '295px', whiteSpace: 'normal', fontWeight: 400 }}>
                                    Whether you're looking for a simple brochure website or a dynamic e-commerce platform, we have the skills and experience to deliver a responsive website that meets your needs and fulfills your desires.
                                </div>
                                {/* LAYER NR. 25 */}
                                <a className="tp-caption Agency-SmallLink   tp-resizeme rs-parallaxlevel-3 text-white" href="about.php" target="_self" id="slide-17-layer-6" data-x="['right','right','center','center']" data-hoffset="['235','80','-25','-25']" data-y="['middle','middle','top','top']" data-voffset="['136','109','392','382']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-actions data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2300,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;300&quot;,&quot;ease&quot;:&quot;Power1.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgba(255,255,255,1);bc:rgb(248,185,32);bw:0 0 2px 0;&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[5,5,5,5]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 111, whiteSpace: 'nowrap', borderColor: 'rgba(221,221,221,0.11)', cursor: 'pointer', textDecoration: 'none' }}>Read
                                    more <span className="fa fa-arrow-right" style={{ fontSize: '12px', color: '#F8B920', marginLeft: '8px' }}>
                                    </span> </a>
                                {/* LAYER NR. 26 */}
                                <div className="tp-caption Agency-NavButton rev-btn  tp-resizeme rs-parallaxlevel-3" id="slide-17-layer-8" data-x="['right','right','center','center']" data-hoffset="['72','52','175','167']" data-y="['middle','middle','top','top']" data-voffset="['230','200','181','172']" data-fontsize="['20','20','17','20']" data-color="['rgb(34,34,34)','rgb(34,34,34)','rgba(109,177,155,1)','rgb(34,34,34)']" data-width={50} data-height={50} data-whitespace="nowrap" data-type="button" data-actions="[{&quot;event&quot;:&quot;click&quot;,&quot;action&quot;:&quot;jumptoslide&quot;,&quot;slide&quot;:&quot;previous&quot;,&quot;delay&quot;:&quot;&quot;}]" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2400,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;300&quot;,&quot;ease&quot;:&quot;Power1.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgb(255,255,255);bg:rgb(34,34,34);bs:solid;bw:0 0 0 0;&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 16, minWidth: '50px', maxWidth: '50px', whiteSpace: 'nowrap', fontFamily: 'Arial', borderColor: 'rgba(0,0,0,1)', outline: 'none', boxShadow: 'none', boxSizing: 'border-box', MozBoxSizing: 'border-box', WebkitBoxSizing: 'border-box', cursor: 'pointer' }}>
                                    <i className="fas fa-angle-left" />
                                </div>
                                {/* LAYER NR. 27 */}
                                <div className="tp-caption Agency-NavButton rev-btn  tp-resizeme rs-parallaxlevel-3" id="slide-17-layer-7" data-x="['right','right','center','center']" data-hoffset="['20','0','175','167']" data-y="['middle','middle','top','top']" data-voffset="['230','200','130','120']" data-width={50} data-height={50} data-whitespace="nowrap" data-type="button" data-actions="[{&quot;event&quot;:&quot;click&quot;,&quot;action&quot;:&quot;jumptoslide&quot;,&quot;slide&quot;:&quot;next&quot;,&quot;delay&quot;:&quot;&quot;}]" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2500,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;300&quot;,&quot;ease&quot;:&quot;Power1.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgba(255,255,255,1);bg:rgb(34,34,34);bs:solid;bw:0 0 0 0;&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 17, minWidth: '50px', maxWidth: '50px', whiteSpace: 'nowrap', fontFamily: 'Arial', borderColor: 'rgba(0,0,0,1)', outline: 'none', boxShadow: 'none', boxSizing: 'border-box', MozBoxSizing: 'border-box', WebkitBoxSizing: 'border-box', cursor: 'pointer' }}>
                                    <i className="fas fa-angle-right" />
                                </div>
                            </li>
                            {/* SLIDE  */}
                            <li data-index="rs-18" data-transition="slideoverdown" data-slotamount="default" data-hideafterloop={0} data-hideslideonmobile="off" data-easein="Power3.easeInOut" data-easeout="Power3.easeInOut" data-masterspeed={1500} data-rotate={0} data-saveperformance="off" data-title="Ideas" data-param1 data-param2 data-param3 data-param4 data-param5 data-param6 data-param7 data-param8 data-param9 data-param10 data-description>
                                {/* MAIN IMAGE */}
                                <img src="images/revoulation/dummy.webp" alt="" data-lazyload="images/revoulation/banner.webp" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax={5} className="rev-slidebg lazy" data-no-retina />
                                {/* LAYERS */}
                                {/* LAYER NR. 28 */}
                                <div className="tp-caption   tp-resizeme rs-parallaxlevel-3" id="slide-18-layer-17" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['250','250','250','250']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1400,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.8;sY:0.8;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 5 }}>
                                    <div className="rs-looped rs-pendulum" data-easing data-startdeg={-60} data-enddeg={60} data-speed={4} data-origin="50% 50%"><img src="images/revoulation/dummy.webp" alt="" data-ww="['163px','163px','163px','163px']" data-hh="['166px','166px','166px','166px']" data-lazyload="images/revoulation/slider-agency-website-slide-01-image-02.webp" data-no-retina className="one lazy" data-speed="0.08" data-revert="true" />
                                    </div>
                                </div>
                                {/* LAYER NR. 29 */}
                                <div className="tp-caption   tp-resizeme" id="slide-18-layer-20" data-x="['right','right','right','right']" data-hoffset="['300','300','300','300']" data-y="['top','top','top','top']" data-voffset="['-100','-100','-100','-100']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="off" data-frames="[{&quot;delay&quot;:1400,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power2.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 6 }}>
                                    <div className="rs-looped rs-slideloop" data-easing data-speed={4} data-xs={0} data-xe={0} data-ys={-20} data-ye={20}><img src="images/revoulation/dummy.webp" alt="" data-ww="['306px','306px','306px','306px']" data-hh="['307px','307px','307px','307px']" className="lazy" data-lazyload="images/revoulation/slider-agency-website-slide-03-image-02.webp" data-no-retina /> </div>
                                </div>
                                {/* LAYER NR. 30 */}
                                <div className="tp-caption   tp-resizeme rs-parallaxlevel-2" id="slide-18-layer-18" data-x="['right','right','right','right']" data-hoffset="['130','130','130','130']" data-y="['bottom','bottom','bottom','bottom']" data-voffset="['0','0','0','0']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1500,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.8;sY:0.8;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 7 }}>
                                    <div className="rs-looped rs-wave" data-speed={3} data-angle={0} data-radius={10} data-origin="50% 50%"><img src="images/revoulation/dummy.webp" alt="" data-ww="['160px','160px','160px','160px']" data-hh="['162px','162px','162px','162px']" data-lazyload="images/revoulation/slider-agency-website-slide-03-image-04.webp" data-no-retina className="one lazy" data-speed="0.08" data-revert="true" />
                                    </div>
                                </div>
                                {/* LAYER NR. 31 */}
                                <div className="tp-caption   tp-resizeme rs-parallaxlevel-2" id="slide-18-layer-19" data-x="['left','left','left','left']" data-hoffset="['200','200','200','200']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1600,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.8;sY:0.8;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 8 }}>
                                    <div className="rs-looped rs-pulse" data-easing data-speed={2} data-zoomstart=".9" data-zoomend={1}><img src="images/revoulation/dummy.webp" alt="" data-ww="['222px','222px','222px','222px']" data-hh="['223px','223px','223px','223px']" data-lazyload="images/revoulation/slider-agency-website-slide-03-image-03.webp" data-no-retina className="one lazy" data-speed="0.08" data-revert="true" />
                                    </div>
                                </div>
                                {/* LAYER NR. 32 */}
                                <div className="tp-caption   tp-resizeme" id="slide-18-layer-16" data-x="['center','center','center','right']" data-hoffset="['-250','-250','-250','100']" data-y="['bottom','bottom','bottom','bottom']" data-voffset="['0','0','0','0']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-basealign="slide" data-responsive_offset="off" data-frames="[{&quot;delay&quot;:1500,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 9 }}><img src="images/revoulation/dummy.webp" alt="" data-ww="['405px','300px','300px','200px']" className="lazy" data-hh="['743px','550px','550px','367px']" data-lazyload="images/revoulation/slider-agency-website-slide-03-image-01.webp" data-no-retina /> </div>
                                {/* LAYER NR. 33 */}
                                <div className="tp-caption tp-shape tp-shapewrapper  tp-resizeme rs-parallaxlevel-3" id="slide-18-layer-3" data-x="['right','right','center','center']" data-hoffset="['20','0','0','-25']" data-y="['middle','middle','top','top']" data-voffset="['0','-20','130','120']" data-width={350} data-height={350} data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1500,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 10, backgroundColor: 'rgb(34,34,34)' }}>
                                </div>
                                {/* LAYER NR. 34 */}
                                <div className="tp-caption Agency-SmallTitle   tp-resizeme rs-parallaxlevel-3 text-white" id="slide-18-layer-4" data-x="['right','right','center','center']" data-hoffset="['42','20','0','-25']" data-y="['middle','middle','top','top']" data-voffset="['-89','-98','164','154']" data-width={295} data-height="none" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2000,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 11, minWidth: '295px', maxWidth: '295px', whiteSpace: 'normal', textTransform: 'uppercase' }}>
                                    SERVICES THAT <br /> DRIVE RESULTS
                                </div>
                                {/* LAYER NR. 35 */}
                                <div className="tp-caption Agency-SmallContent   tp-resizeme rs-parallaxlevel-3 text-white" id="slide-18-layer-5" data-x="['right','right','center','center']" data-hoffset="['40','20','0','-25']" data-y="['middle','middle','top','top']" data-voffset="['20','-3','300','245']" data-width={295} data-height="none" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2150,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 12, minWidth: '295px', maxWidth: '295px', whiteSpace: 'normal' }}>
                                    Our highly trained personnel provides a full range of digital services, from design and development to branding and marketing, and we can cater to each customer's needs.
                                </div>
                                {/* LAYER NR. 36 */}
                                <a className="tp-caption Agency-SmallLink   tp-resizeme rs-parallaxlevel-3 text-white" href="about.php" target="_self" id="slide-18-layer-6" data-x="['right','right','center','center']" data-hoffset="['235','201','0','-25']" data-y="['middle','middle','top','top']" data-voffset="['108','107','392','382']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-actions data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2300,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;300&quot;,&quot;ease&quot;:&quot;Power1.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgba(255,255,255,1);bc:rgb(248,185,32);bw:0 0 2px 0;&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[5,5,5,5]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 111, whiteSpace: 'nowrap', borderColor: 'rgba(221,221,221,0.11)', cursor: 'pointer', textDecoration: 'none' }}>Read
                                    more <span className="fa fa-arrow-right" style={{ fontSize: '12px', color: '#F8B920', marginLeft: '8px' }}>
                                    </span> </a>
                                {/* LAYER NR. 37 */}
                                <div className="tp-caption Agency-NavButton rev-btn  tp-resizeme rs-parallaxlevel-3" id="slide-18-layer-8" data-x="['right','right','center','center']" data-hoffset="['72','52','202','175']" data-y="['middle','middle','top','top']" data-voffset="['202','182','182','171']" data-width={50} data-height={50} data-whitespace="nowrap" data-type="button" data-actions="[{&quot;event&quot;:&quot;click&quot;,&quot;action&quot;:&quot;jumptoslide&quot;,&quot;slide&quot;:&quot;previous&quot;,&quot;delay&quot;:&quot;&quot;}]" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2400,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;300&quot;,&quot;ease&quot;:&quot;Power1.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgba(255,255,255,1);bg:rgb(34,34,34);bs:solid;bw:0 0 0 0;&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 14, minWidth: '50px', maxWidth: '50px', whiteSpace: 'nowrap', fontFamily: 'Arial', borderColor: 'rgba(0,0,0,1)', outline: 'none', boxShadow: 'none', boxSizing: 'border-box', MozBoxSizing: 'border-box', WebkitBoxSizing: 'border-box', cursor: 'pointer' }}>
                                    <i className="fas fa-angle-left" />
                                </div>
                                {/* LAYER NR. 38 */}
                                <div className="tp-caption Agency-NavButton rev-btn  tp-resizeme rs-parallaxlevel-3" id="slide-18-layer-7" data-x="['right','right','center','center']" data-hoffset="['20','0','202','175']" data-y="['middle','middle','top','top']" data-voffset="['202','182','130','120']" data-width={50} data-height={50} data-whitespace="nowrap" data-type="button" data-actions="[{&quot;event&quot;:&quot;click&quot;,&quot;action&quot;:&quot;jumptoslide&quot;,&quot;slide&quot;:&quot;next&quot;,&quot;delay&quot;:&quot;&quot;}]" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:2500,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:3000,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power4.easeIn&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;300&quot;,&quot;ease&quot;:&quot;Power1.easeInOut&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgba(255,255,255,1);bg:rgb(34,34,34);bs:solid;bw:0 0 0 0;&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 15, minWidth: '50px', maxWidth: '50px', whiteSpace: 'nowrap', fontFamily: 'Arial', borderColor: 'rgba(0,0,0,1)', outline: 'none', boxShadow: 'none', boxSizing: 'border-box', MozBoxSizing: 'border-box', WebkitBoxSizing: 'border-box', cursor: 'pointer' }}>
                                    <i className="fas fa-angle-right" />
                                </div>
                            </li>
                        </ul>
                        <div style={{}} className="tp-static-layers">
                      
                            {/* LAYER NR. 41 */}
                            <div className="tp-caption   tp-resizeme tp-static-layer" id="slider-6-layer-16" data-x="['left','left','left','left']" data-hoffset="['70','70','70','70']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width={30} data-height="none" data-whitespace="normal" data-visibility="['on','on','off','off']" data-type="text" data-basealign="slide" data-responsive_offset="on" data-startslide={0} data-endslide={2} data-frames="[{&quot;delay&quot;:2000,&quot;split&quot;:&quot;chars&quot;,&quot;splitdelay&quot;:0.05,&quot;speed&quot;:2000,&quot;split_direction&quot;:&quot;forward&quot;,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:[100%];z:0;rZ:-35deg;sX:1;sY:1;skX:0;skY:0;&quot;,&quot;mask&quot;:&quot;x:0px;y:0px;s:inherit;e:inherit;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 45, minWidth: '30px', maxWidth: '30px', whiteSpace: 'normal', fontSize: '24px', lineHeight: '70px', fontWeight: 800, color: '#ffffff', textTransform: 'uppercase' }}>
                                D<span style={{ display: 'block', fontSize: '24px', fontWeight: 800, marginLeft: '4px' }}>I</span>V E
                                R <span style={{ display: 'block', fontSize: '24px', fontWeight: 800 }}>S</span><span style={{ display: 'block', fontSize: '24px', fontWeight: 800, marginLeft: '4px' }}>I</span><span style={{ display: 'block', fontSize: '24px', fontWeight: 800 }}>T</span> Y
                            </div>
                            {/* LAYER NR. 42 */}
                            <div className="tp-caption    slide-status-numbers tp-static-layer" id="slider-6-layer-18" data-x="['right','right','right','right']" data-hoffset="['60','60','60','60']" data-y="['middle','middle','middle','middle']" data-voffset="['-110','-110','-110','-110']" data-width={37} data-height="none" data-whitespace="normal" data-visibility="['on','on','off','off']" data-type="text" data-basealign="slide" data-responsive_offset="off" data-responsive="off" data-startslide={0} data-endslide={2} data-frames="[{&quot;delay&quot;:0,&quot;speed&quot;:300,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 46, minWidth: '37px', maxWidth: '37px', whiteSpace: 'normal', fontSize: '36px', lineHeight: '51px', fontWeight: 700, color: '#ffffff', fontFamily: 'Poppins' }}>
                                01
                            </div>
                            {/* LAYER NR. 43 */}
                            <div className="tp-caption tp-shape tp-shapewrapper  tp-static-layer" id="slider-6-layer-19" data-x="['right','right','right','right']" data-hoffset="['74','74','74','74']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width={3} data-height={150} data-whitespace="normal" data-visibility="['on','on','off','off']" data-type="shape" data-basealign="slide" data-responsive_offset="off" data-responsive="off" data-startslide={0} data-endslide={2} data-frames="[{&quot;delay&quot;:0,&quot;speed&quot;:300,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 47, backgroundColor: 'rgb(255,255,255)' }}>
                            </div>
                            {/* LAYER NR. 44 */}
                            <div className="tp-caption   tp-static-layer" id="slider-6-layer-20" data-x="['right','right','right','right']" data-hoffset="['62','62','62','62']" data-y="['middle','middle','middle','middle']" data-voffset="['110','110','110','110']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="text" data-basealign="slide" data-responsive_offset="off" data-responsive="off" data-startslide={0} data-endslide={2} data-frames="[{&quot;delay&quot;:0,&quot;speed&quot;:300,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{ zIndex: 48, whiteSpace: 'nowrap', fontSize: '20px', lineHeight: '28px', fontWeight: 700, color: '#ffffff', fontFamily: 'Poppins' }}>
                                03
                            </div>
                        </div>
                        <div className="tp-bannertimer tp-bottom" style={{ visibility: 'hidden !important' }} />
                    </div>
                </div>
                {/* End REVOLUTION SLIDER */}
            </div>
            {/* home banner end */}
        </>
    )
}

export default Banner